# Generated by Django 5.2.11 on 2026-09-30 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descriptons',
            new_name='descripton',
        ),
    ]
