# Generated by Django 5.2.11 on 2026-09-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_rename_descriptons_category_descripton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descripton',
            new_name='description',
        ),
    ]
